logging:
  level:
#    root: TRACE
    web: TRACE
#    org.springframework.web: TRACE
#    org.hibernate: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
#deprected
#spring:
#  security:
#    user:
#      name: david
#      password: qwe123
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true